### ISSUE TITLE
Rebooting due to Unhandled C++ exception: std::bad_alloc

### ISSUE THREAD

**Issue by wfraga18** [brownjd/ESPStockTicker#1]
Hello, 

Your idea is so cool

I'm trying to test by the first time..
Do you know what's causing that ?

setupIPHandlers()...
setupIPHandlers()...done
connectWifi()...
readWifiInfo()...
ROUTER : password0123
readWifiInfo()...done
setupMDNS()...
updateHostName()...
New hostname: esp
updateHostName()...done
hostname: esp
setupMDNS()...done
startSoftAP()...
startSoftAP()...done
connectWifi()...done
Reading ticker file...
Reading ticker file...done
queryPrices()...
Pricing API GET URL: GET /1.0/stock/market/batch?filter=latestPrice,changePercent&types=quote&displayPercent=true&symbols=AMZN,MSFT,APPL,BAC, HTTP/1.0
Host: api.iextrading.com
User-Agent: ESP8266
Connection: close

Remote host unreachable: api.iextrading.com
queryPrices()...done
queryChartInfo()...
API Chart GET URL: GET /1.0/stock/XPO/chart/1d?chartInterval=2&filter=average HTTP/1.0
Host: api.iextrading.com
User-Agent: ESP8266
Connection: close

Unhandled C++ exception: std::bad_alloc

>>>stack>>>

ctx: cont
sp: 3ffffb60 end: 3fffffc0 offset: 01b0
3ffffd10:  00000000 00000000 00000000 40222a44  
3ffffd20:  40000000 00000000 00000000 4022b534  
3ffffd30:  00000000 00000000 00000000 00000000  
3ffffd40:  3ffe8f0a 000001bb 3fffb4fc 4022b575  
3ffffd50:  3fffb4fc 4022bc74 3fffb4fc 4022bceb  
3ffffd60:  c014c00a 00000bf8 00000bf8 4022be75  
3ffffd70:  c02ac026 c00ec004 3ffffda0 4020f85c  
3ffffd80:  c09dc09c c0a1c0a0 003d003c 0035002f  
3ffffd90:  c012c008 3ffffe90 3ffffe90 4020fe33  
3ffffda0:  00000000 00000000 3ffffe90 000001bb  
3ffffdb0:  3ffe8f0a 3ffffe90 3ffffe90 402103c1  
3ffffdc0:  00000000 3ffffe20 4021e018 3fffefa0  
3ffffdd0:  00000000 00000000 000007d0 402016a7  
3ffffde0:  00000000 3ffffe90 3fff495c 4020f0aa  
3ffffdf0:  000001bb 3ffe8df4 00000000 000001bb  
3ffffe00:  000001bb 3ffffe90 3ffe8f0a 000001bb  
3ffffe10:  000001bb 3ffffe90 3ffe8f0a 40210552  
3ffffe20:  40220ba8 7ba7e023 3ffffe90 4021e0f6  
3ffffe30:  3ffef8e8 3ffe8f0a 3ffffe90 40207c35  
3ffffe40:  00000000 00000000 3ffef7b4 3fff17bc  
3ffffe50:  3ffe8f0a 402010a3 000015e0 401007fc  
3ffffe60:  00000000 00000000 3ffffe90 402010a3  
3ffffe70:  00000080 00000000 3ffffe90 3fff17bc  
3ffffe80:  3ffe8f0a 3ffef8e8 3ffe8f60 4020c744  
3ffffe90:  40220800 00000000 000007d0 3fff4998  
3ffffea0:  3ffef828 3fff495c 3fff63b4 3fff4994  
3ffffeb0:  00000000 00000000 3fff63b4 00000000  
3ffffec0:  00000000 00000000 00000000 00000000  
3ffffed0:  00000000 3fff710c 3fff49c4 3fffb25c  
3ffffee0:  3fff6214 00000000 00000000 00000000  
3ffffef0:  00004145 00000255 3fff0000 00000000  
3fffff00:  3fff0000 0000051d 0000051d 3fff17bc  
3fffff10:  3ffef7f8 00000089 00000000 4021c1c8  
3fffff20:  00000000 3ffef800 00000000 00000000  
3fffff30:  3ffe8ca9 00000000 3fffff70 4021c535  
3fffff40:  3ffef800 3fff185a 3fff1970 4021c624  
3fffff50:  3fff4958 4021bb98 3fff1970 4021c698  
3fffff60:  3ffe8550 3ffef8e8 3fff1970 4020ca19  
3fffff70:  00000000 00000000 00000000 3fffefa0  
3fffff80:  00000000 00000000 3ffef800 3fff1a94  
3fffff90:  3ffef7f8 3fff185a 3ffef800 4020ce08  
3fffffa0:  3fffdad0 00000000 3fff1a60 4021e0c4  
3fffffb0:  feefeffe feefeffe 3ffe8694 40100a4d  
<<<stack<<<

last failed alloc call: 40223535(3088)

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

thank you

**Comment by brownjd** [comment]
Can you give me some more information of what is happening? Do you have a stack trace?


Jb

**Comment by wfraga18** [comment]
How can i provide you that info ? I don't know how to stack trace on arduino

**Comment by brownjd** [comment]
Thanks for posting the trace. 

First issue is see is: Remote host unreachable: api.iextrading.com

So it isn't getting stock prices. I suspect it is crashing on the second try for the graph data, probably because it is failing to connect to the iextrading api and I'm not catching the error before trying to use the data. I'll run a few tests to confirm...

Bottom line, your ESP is not connecting to the outside world. Is it successfully getting a good IP address?

**Comment by wfraga18** [comment]
yes it is

**Comment by wfraga18** [comment]
yes, it connected, but still

maybe something changes on API ? are yours working ?


Remote host unreachable: api.iextrading.com
queryPrices()...done
queryPrices()...
Pricing API GET URL: GET /1.0/stock/market/batch?filter=latestPrice,changePercent&types=quote&displayPercent=true&symbols=SPY,QQQ,BAC,CVX,ED,DWDP,GE,GILD,HTH,KMB,JNJ,SBSI,INTC, HTTP/1.0
Host: api.iextrading.com
User-Agent: ESP8266
Connection: close

**Comment by wfraga18** [comment]
Our problem is:  the new API demands use for HTTPS, means, esp8266 don't work for that

**Comment by wfraga18** [comment]
using postman with HTTPS, i was able to retrieve:
( but HTTP, is not functional )

{
    "SPY": {
        "quote": {
            "latestPrice": 265.78,
            "changePercent": 0.8460000000000001
        }
    },
    "QQQ": {
        "quote": {
            "latestPrice": 165.15,
            "changePercent": 1.195
        }
    },
    "BAC": {
        "quote": {
            "latestPrice": 29.58,
            "changePercent": 1.719
        }
    },
    "CVX": {
        "quote": {
            "latestPrice": 113.22,
            "changePercent": -0.255
        }
    },
    "ED": {
        "quote": {
            "latestPrice": 75.95,
            "changePercent": -2.202
        }
    },
    "DWDP": {
        "quote": {
            "latestPrice": 57.76,
            "changePercent": 2.539
        }
    },
    "GE": {
        "quote": {
            "latestPrice": 9.16,
            "changePercent": 4.328
        }
    },
    "GILD": {
        "quote": {
            "latestPrice": 68.9,
            "changePercent": 1.533
        }
    },
    "HTH": {
        "quote": {
            "latestPrice": 18.71,
            "changePercent": -3.4070000000000005
        }
    },
    "KMB": {
        "quote": {
            "latestPrice": 108.12,
            "changePercent": -2.979
        }
    },
    "JNJ": {
        "quote": {
            "latestPrice": 128.23,
            "changePercent": 0.9450000000000001
        }
    },
    "SBSI": {
        "quote": {
            "latestPrice": 34.26,
            "changePercent": -0.291
        }
    },
    "INTC": {
        "quote": {
            "latestPrice": 47.04,
            "changePercent": -5.466
        }
    }
}

**Comment by brownjd** [comment]
Mine is working fine with HTTPS. I haven’t been able to debug the code yet because I’ve been having trouble getting my serial port to show up. As soon as I do, I’ll let you know what I find.


Jb

**Comment by wfraga18** [comment]
I spent hours today, changing everything,  the only request that are working is for the TBILL, since is a port 80
the requests for 443 are returning no conection and when I try fake a 443 I get
<html>
    <head>
        <title>400 The plain HTTP request was sent to HTTPS port</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>400 Bad Request</h1>
        </center>
        <center>The plain HTTP request was sent to HTTPS port</center>
        <hr>
        <center>nginx</center>
    </body>
</html>


Are you running the same version on github ? something is weird

**Comment by wfraga18** [comment]
Forgot everything, the problem was LAST 3 versions of ESP8266,  I downgraded for 2.4 and works

**Comment by wfraga18** [comment]
I found ! the problem: the LAST 3 versions of ESP8266,  I downgraded for 2.4 and works

**Comment by brownjd** [comment]
Awesome, what version were you using?

Also, how were the directions getting started?


Jb

**Comment by wfraga18** [comment]
2.5> don't work 
those have a lot of issues with wifi methods

**Comment by brownjd** [comment]
Looks like 2.5.x are still in beta, so yeah, I would stick with 2.4.2 for now. I'll see what it required to support 2.5

**Comment by brownjd** [comment]
I've updated the readme to specify which versions of the libraries have been tested.

**Comment by wfraga18** [comment]
Hey Brown,  I wanna invite you for a new project that I'm willing to do, A new ticker for ESP32 ( about same price and more suitable for the task)
How can I contact you ?

**Comment by brownjd** [comment]
Send me a link to the project. I’d love to take a look.


Jb
